# Generated by Django 5.0.3 on 2024-03-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('Book_Title', models.CharField(max_length=255)),
                ('Book_Author', models.CharField(max_length=255)),
                ('Year_Of_Publication', models.IntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('Image_URL_S', models.URLField()),
                ('Image_URL_M', models.URLField()),
                ('Image_URL_L', models.URLField()),
            ],
        ),
    ]
