# Generated by Django 5.0.3 on 2024-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField()),
                ('ISBN', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Year', models.IntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('Image_URL_L', models.URLField()),
                ('num_of_rating', models.IntegerField()),
            ],
        ),
    ]
