# Generated by Django 5.0.3 on 2024-04-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_final_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='User',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
