# Generated by Django 5.0.3 on 2024-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_rating_isbn_remove_rating_user_delete_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_rating',
            name='Image_URL_L',
            field=models.CharField(max_length=255),
        ),
    ]
