# Generated by Django 5.0.3 on 2024-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_final_rating_image_url_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_rating',
            name='ISBN',
            field=models.CharField(max_length=255),
        ),
    ]
